### ISSUE TITLE
After the last update, Custom Boot Display stopped working

### ISSUE THREAD

**Issue by GrayNexTry** [KORSiRO/Custom-Boot-Display-K1-K1Max#1]
After the last update, Custom Boot Display stopped working. Creality K1C does not log in, does not open ports, does not connect. Only the creality logo is displayed and the lamp lights up. Can you tell me how to reset it to factory defaults without going to a service center?

**Comment by KORSiRO** [comment]
Was your printer rooted if you installed a custom boot display? it was indicated that the printer had to be factory reset before doing the update
![IMG_0367](https://github.com/KORSiRO/Custom-Boot-Display-K1-K1Max/assets/62854582/6438d47d-eeb9-4c7e-8f25-878d42c41af3)

**Comment by GrayNexTry** [comment]
My procedure was as follows: reset the printer, rooted it, installed mainsail, ngix, then installed Custom Boot Display and restarted the printer. Since then, it won't start

**Comment by GrayNexTry** [comment]
If there are instructions on how to reset without logging in, I would appreciate it. I found an rst button on the motherboard, but I'm afraid it will completely clean the linux system

**Comment by KORSiRO** [comment]
after discussing with Guilouz there was no change on the boot display on the last update. so the problem does not come from there

**Comment by GrayNexTry** [comment]
ok, i got it, thx
